// apps/we/src/renderers/componentRegistry.tsx
import { CircleButton, Column, PopoverMenu, Row } from '@we/components/solid';
import { HomePage, PageNotFound } from '@we/pages/solid';
import { DefaultTemplate } from '@we/templates/solid';
import { CreateSpaceModalWidget } from '@we/widgets/solid';
import { JSX } from 'solid-js';

export type ComponentRegistry = {
  [key: string]: (props: any) => JSX.Element;
};

export const componentRegistry: ComponentRegistry = {
  // Elements
  'we-text': (props) => <we-text>{props.children}</we-text>,

  // Components
  Column,
  Row,
  CircleButton,
  PopoverMenu,

  // Widgets
  CreateSpaceModalWidget,

  // Pages
  PageNotFound,
  HomePage,

  // Templates
  DefaultTemplate,
};

// apps/we/src/registries/componentRegistry.tsx
import { CircleButton, Column, PopoverMenu, Row } from '@we/components/solid';
import { HomePage, PageNotFound, SpacePage } from '@we/pages/solid';
import type { ComponentRegistry } from '@we/schema-renderer/solid';
import { DefaultTemplate } from '@we/templates/solid';
import { CreateSpaceModalWidget, SpaceSidebarWidget } from '@we/widgets/solid';

export const componentRegistry: ComponentRegistry = {
  // @we/elements
  'we-text': (props) => <we-text {...props}>{props.children}</we-text>,
  'we-button': (props) => <we-button {...props}>{props.children}</we-button>,

  // @we/components
  Column,
  Row,
  CircleButton,
  PopoverMenu,

  // @we/widgets
  CreateSpaceModalWidget,
  SpaceSidebarWidget,

  // @we/pages
  PageNotFound,
  HomePage,
  SpacePage,

  // @we/templates
  DefaultTemplate,
};
